{{- if and .Values.keycloak.enabled (not .Values.keycloak.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-keycloak-admin
  labels:
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.keycloak.admin.usernameKey }}: {{ .Values.keycloak.admin.username | quote }}
  {{ .Values.keycloak.admin.passwordKey }}: {{ .Values.keycloak.admin.password | quote }}
{{- end }}
