{{- if and .Values.keycloak.enabled .Values.keycloak.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-keycloak-data
  labels:
    app.kubernetes.io/component: keycloak
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.keycloak.persistence.accessModes | nindent 4 }}
  {{- if or .Values.keycloak.persistence.storageClass .Values.global.storageClass }}
  storageClassName: {{ default .Values.global.storageClass .Values.keycloak.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.keycloak.persistence.size }}
{{- end }}
