{{- if and .Values.keycloak.enabled (include "eudi-wallet-demo.usePostgres" . | eq "true") (not .Values.keycloak.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eudi-wallet-demo.dbSecretName" . }}
  labels:
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ ternary .Values.postgresql.auth.username .Values.keycloak.database.username .Values.postgresql.enabled | quote }}
  {{ .Values.keycloak.database.passwordKey }}: {{ ternary .Values.postgresql.auth.password .Values.keycloak.database.password .Values.postgresql.enabled | quote }}
  database: {{ ternary .Values.postgresql.auth.database .Values.keycloak.database.name .Values.postgresql.enabled | quote }}
{{- end }}
