{{- if and .Values.keycloak.enabled .Values.keycloak.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-keycloak
  labels:
    app.kubernetes.io/component: keycloak
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
  {{- with .Values.keycloak.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.keycloak.ingress.className }}
  ingressClassName: {{ .Values.keycloak.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.keycloak.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "eudi-wallet-demo.fullname" $ }}-keycloak
                port:
                  number: {{ $.Values.keycloak.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.keycloak.ingress.tls }}
  tls:
    {{- toYaml .Values.keycloak.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
