{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-keycloak
  labels:
    app.kubernetes.io/component: keycloak
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
  {{- with .Values.keycloak.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - name: http
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: keycloak
    {{- include "eudi-wallet-demo.selectorLabels" . | nindent 4 }}
{{- end }}
