{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-realm
  labels:
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  realm-export.json: |
{{ .Files.Get .Values.keycloak.realmFile | indent 4 }}
{{- end }}
