{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-postgresql
  labels:
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
  selector:
    app.kubernetes.io/component: postgresql
    {{- include "eudi-wallet-demo.selectorLabels" . | nindent 4 }}
{{- end }}
