{{- if and .Values.serviceAccount.create (or .Values.keycloak.enabled .Values.wallet.enabled .Values.postgresql.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eudi-wallet-demo.serviceAccountName" . }}
  labels:
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
{{- end }}
