{{- if .Values.wallet.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-wallet-keys
  labels:
    app.kubernetes.io/component: wallet
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  wallet-keys.json: |
{{ .Files.Get "files/wallet/wallet-keys.json" | indent 4 }}
  verifier-keys.json: |
{{ .Files.Get "files/wallet/verifier-keys.json" | indent 4 }}
  mock-issuer-keys.json: |
{{ .Files.Get "files/wallet/mock-issuer-keys.json" | indent 4 }}
{{- end }}
