{{- if and .Values.wallet.enabled (not .Values.wallet.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-wallet
  labels:
    app.kubernetes.io/component: wallet
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.wallet.secrets.oidcClientSecretKey }}: {{ .Values.wallet.keycloak.clientSecret | quote }}
{{- end }}
