{{- if .Values.wallet.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eudi-wallet-demo.fullname" . }}-wallet-config
  labels:
    app.kubernetes.io/component: wallet
    {{- include "eudi-wallet-demo.labels" . | nindent 4 }}
data:
  mock-issuer-configurations.json: |
{{ .Files.Get "files/wallet/mock-issuer-configurations.json" | indent 4 }}
{{- end }}
