name: Build and push image
on:
  push:
    tags: '**'
  workflow_dispatch: { }

jobs:
  build-and-push-image:
    # Run only for the ba-itsys organization
    if: github.repository_owner == 'ba-itsys'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push image'
        run: >
          mvn
          --batch-mode
          -DskipTests
          -pl demo-app
          -am
          -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:\${project.version}
          -Dspring-boot.build-image.publish=true
          spring-boot:build-image
